### ISSUE TITLE
Bug: git head build error: missing file: cal/w2f.cal

### ISSUE THREAD

**Issue by gene-git** [lcn2/calc#100]
Calc bug report template version: 1.3 2022-11-27

Git head as of commit 20ce75a06dd90c22cdc83a9258f96aac5bd76be9 fails to build due to missing file cal/w2f.cal:

  make[1]: *** No rule to make target 'w2f.cal', needed by 'all'.  Stop.

**Comment by lcn2** [comment]
Hello @gene-git,

Our mistake.  We had a test code in the source directory and forgot to remove it before rebuilding the file list.

You can temporarily just create an empty file `cal/w2f.cal` to work around it.

Right now we are away from the repository, otherwise we'd fix it immediately. Later today we will either remote it from the official list, or add it as useful example of FILE I/O. 

Thanks for letting us know!

**Comment by lcn2** [comment]
Hello @gene-git,

Fixed with commit b55d41c221f125dda258013e42d943fca62b3a0d.

Thanks for the bug report!

**Comment by gene-git** [comment]
had changed my build script to create the missing file if not found after git pull.  
I confirm it's now fixed too. 

thank you!
