### ISSUE TITLE
Enhancement: read/write json

### ISSUE THREAD

**Issue by ghost** [lcn2/calc#121]
Read/Write JSON.

**Comment by lcn2** [comment]
What would be the purpose for writing JSON files?   What should happen when a JSON file is read by calc?

Can you give a usage case for JSON file reading and writing?

**Comment by kcrossen** [comment]
There are likely a few open source packages that meet this need. In Python, Simple JSON traverses via recursive descent a dict object, generating the serializable text form. Notably, this does not handle date/time/datetime data despite the existence of an official ISO format. This deficiency is trivially fixed. Have never researched this for C/C++.

**Comment by lcn2** [comment]
> There are likely a few open source packages that meet this need. In Python, Simple JSON traverses via recursive descent a dict object, generating the serializable text form. Notably, this does not handle date/time/datetime data despite the existence of an official ISO format. This deficiency is trivially fixed. Have never researched this for C/C++.

The question is NOT about how to read and write JSON.

In terms of reading JSON there are C based JSON parsers such as [jparse](https://github.com/xexyl/jparse) that can validate and read JSON.

And since calc has a general I/O routines, technically calc is capable of writing strings that are valid JSON.  Sure, calc could make use of the [jparse](https://github.com/xexyl/jparse) code to encode JSON strings for writing, etc.  And perhaps there could be more direct support for in calc for writing JSON.

The question that was ASK in [comment 1767451139](https://github.com/lcn2/calc/issues/121#issuecomment-1767451139) was asking **WHY** add JSON?  It was asking for a reasonable **USE CASE**.  It was asking about what calc would do in both reading and writing JSON.

Reading JSON in calc probably raises more questions.  

Consider this valid JSON:

```json
{
	"foo" : [{
		"foo" : [{
			"bar" : 42
		}]
	}]
}
```

Say somehow that calc "read" that JSON.  What do you expect to happen in calc as a result?

Or consider this valid JSON:

```json
[ 200, 200.0, 2e2, 200.000, 2.0e2, 0.2e3, 20.0e1 ]
```

Say somehow that calc "read" that JSON.  What do you expect to happen in calc as a result?

Or for a more involved use case, consider this valid JSON:

```json
{
    "number":42,
    "value":"value",
    "number_as_str":"42",
    "answer to life, the universe and everything" : 42,
    "panic":false,
    "panic":true,
    "false":true,
    "true":false,
    "killers":"Vogons",
    "Killers":"Vogons",
    "hitchhikers" : [
	    {
		"person" : [
		    {
			"name" : "Arthur Dent",
			"race" : "human",
			"status" : "dead",
			"alive": false
		    },
		    {
			"name": "Ford Prefect",
			"race" : "Betelgeusian",
			"status" : "dead",
			"alive": false
		    }
		]
	    }
    ],
    "Vogons" : [
	    {
		"alien" : [
		    {
			"name" : "Prostetnic Vogon Jeltz",
			"job": "Destroy Earth"
		    }
		]
	    }
    ],
    "value" : [ "value", "value", "value" ],
    "hitch-hikers":"hitchhikers"
}
```

What would one expect to happen if calc read that JSON?

**It is one thing to say "have calc read JSON".  It is another thing to explain what calc would do having read some JSON.**

And calc has general I/O routines to write anything.  Sure, one could add a `cal/write_json.cal` resource file to make it easier to write JSON syntax.  

**Without a general use case to READ JSON and do something with what was read** there isn't a good enough reason to justify the effort to integrate JSON with calc, let alone have a explanation of what calc should do with valid JSON that it has "read".**

**Comment by lcn2** [comment]
Sorry that you, @kcrossen, found the above questions "hostile".

**Comment by kcrossen** [comment]
Can you see that the following:

Reluctantly, given a lack on direct response our questions about "protect"
inheritance from @kcrossen <https://github.com/kcrossen>, we have removed a
related calc v3 TODO.

Sadly we did not see (or somehow missed) a direct replies to our questions
about the feature request. So we have put tbudren on @kcrossen
<https://github.com/kcrossen> to code and submit changes for whatever his
"protect" inheritance is via a GitHub Pull request
<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request>.
(Click the link for GitHub pull request info).

might be interpreted by me as impatient, judgemental, sarcastic,
hair-trigger, ... potentially hostile? Read again our (many months ago)
previous exchange. These current follow a similar (though less extreme)
pattern.

We may value differing qualities in relationships. For me kindness and
compassion are primary, especially as I treat others. I've got some way
left to stumble down that road.

Respectfully,
Ken

**Comment by pmetzger** [comment]
I don't see why one would want this. FWIW, the person who posted the original request seems to have done an awful lot of inexplicable hit and run tickets on various things.

**Comment by lcn2** [comment]
> I don't see why one would want this. FWIW, the person who posted the original request seems to have done an awful lot of inexplicable hit and run tickets on various things.

Thank you.
