### ISSUE TITLE
Bug: 'help usage' shows formatting under macos

### ISSUE THREAD

**Issue by wwk-github** [lcn2/calc#135]
**Describe the bug**
Invoke calc and run 'help usage'.
Under linux (ubuntu) - all OK.
Under macos - formatting is not applied.

**Screen shots**
linux
<img width="565" alt="image" src="https://github.com/lcn2/calc/assets/50773217/46f7167a-280a-4f2d-932a-ae9d1216687f">

macos
<img width="604" alt="image" src="https://github.com/lcn2/calc/assets/50773217/da6e4e6d-0ae7-4e19-ab72-2a67472a7548">

**Comment by lcn2** [comment]
You are correct, @wwk-github.

Probably the best thing ro do is to form what Unix called a "cat page": a formatter man page as part of the build process so that a wider range of page tools will be able to see a reasonably formatted page.  Such a "cat page" would be formed from the `calc.1` file, nroff formatted, and installed under the `help/` directory.

**Comment by lcn2** [comment]
Hello @wwk-github,

We have a fix for your issue that we are testing.  We are testing it at the same time as we are testing a different fix for issue #133.  As soon as our testing is complete we will release a new version of calc and close this issue.

Thank you for your patience.

**Comment by lcn2** [comment]
If you want to see the proposed fix to this issue, check out the master brach for (commit 8e8d6c852ac1b7f85deeed6da03c58f2defe416c or later).

**Comment by lcn2** [comment]
This issue has resolve under calc version 2.15.0.4.

Thank you @wwk-github for bringing this issue to our attention.  We will now close you issue with our thanks!

**Comment by wwk-github** [comment]
Nice. Thank you.

<img width="548" alt="image" src="https://github.com/lcn2/calc/assets/50773217/4b58c009-b3d2-4965-b493-c7a49ea6ecdd">
