### ISSUE TITLE
Radians to degrees

### ISSUE THREAD

**Issue by J053Fabi0** [lcn2/calc#16]
How can I get the results of radians in degrees?

**Comment by lcn2** [comment]
One can always multiple the result of a trig function such as atan() by 180/pi() to convert the radians into degrees.

atan(1) returns pi()/4 because the arc tangent of 1 is pi/4 radians.  If you want 45 degrees. then one must multiply the result by 180/pi.

For example, 

atan(1) * 180 / pi()

returns a value very close to 45 (within the limitation of the approximation of pi by the pi() function) degrees.
