### ISSUE TITLE
Feature request: prebuilt packages

### ISSUE THREAD

**Issue by NJdevPro** [lcn2/calc#23]
Not anyone has a compiler installed. Most people just want to be able to use the tool without the headache of building it.
Consider offering prebuilt packages for Linux/Windows/MacOS ?

Note that Github actions allow to create these builds automatically.

**Comment by lcn2** [comment]
**Thank you @NJdevPro for your excellent suggestions.**

### **Regarding prebuilt packages for Linux:**

The calc packages are pre-built for Linux (and have been for many years).  Each tagged release comes with a set of RPMs that may be installed.

In addition to the tagged GitHub releases:

- https://github.com/lcn2/calc/releases

there are calc mirrors where those same RPMs may be found:

- http://www.isthe.com/chongo/src/calc/
- https://sourceforge.net/projects/calc/files/calc/

For example, the latest v2.12.8.2 base calc RPM is available at:

- https://github.com/lcn2/calc/releases/download/v2.12.8.2/calc-2.12.8.2-13.x86_64.rpm
- http://www.isthe.com/chongo/src/calc/calc-2.12.8.2-13.x86_64.rpm
- https://sourceforge.net/projects/calc/files/calc/2.12.8.2/calc-2.12.8.2-13.x86_64.rpm/download

### **Regarding prebuilt packages for Windows:**

Due to the fact that we cannot agree to Microsoft's Windows licensing terms (on advice of council), we do not have access to any windows operating systems and thus we cannot pre-build any windows packages, **sorry** (tm Canada :-) ).  If someone else wanted to pre-build such packages for windows, we would be happy to share a link to those packages (with suitable disclaimers) in both the repo `README.md`, and in the `REEADME.WINDOWS` source file.

### **Regarding prebuilt packages for macOS:**

The suggestion of pre-building a dmg for macOS is a good one.  We are thinking of obtaining an Apple developer license. We have reviewed Apple's developer terms and we will be able to agree to them.  We have put on our calendar of tasks, building a dmg for macOS in early March to see how it goes.

**Thank you again, @NJdevPro, for your suggestion.**

**Comment by flawrist** [comment]
So there is no pre-compiled binary for Windows users?

**Comment by pmetzger** [comment]
Get Calc added to WinGet perhaps.

**Comment by lcn2** [comment]
> So there is no pre-compiled binary for Windows users?

Hello @sergeevabc 

Sorry (tm Canada 🇨🇦) we do not have access to any Windows systems, nor are we able to accept the Windows EULA.  As such we have no ability to compile calc on windows.

There are others who have built calc on Windows.  In the past they have provided patches with C code surrounded by '#if defined stuff' in places where the base calc code needed to be tweaked for windows.

The `README.WINDOWS` file contains contributions from people who have successfully compiled calc on Windows.

Please see that file for the best way others have told us to build calc under Windows.

We are told that Cygwin is good choice, nevertheless see the `README.WINDOWS` file for more information.

**Comment by lcn2** [comment]
> Get Calc added to WinGet perhaps.

We would appreciate if someone did that, if that helps.

**Comment by pmetzger** [comment]
I personally own no Windows machines; I suspect this is the sort of thing someone who uses  Windows and cares a lot about the platform would have to take on.

**Comment by lcn2** [comment]
> I personally own no Windows machines; I suspect this is the sort of thing someone who uses Windows and cares a lot about the platform would have to take on.

If someone else wishes to build Windows binaries for calc for others to use, we would provide a link to such a location in both the `README.WINDOWS` source file, and in the `README.md` of the calc repo with suitable disclaimers.

**Comment by pmetzger** [comment]
I suggest that the right thing, again, would be for someone with a windows machine and who cares about Windows to submit Calc to WinGet via https://github.com/microsoft/winget-pkgs

**Comment by flawrist** [comment]
@pmetzger WinGet is for Windows 10+, whereas I use and will continue to use Windows 7.

In the meantime, I've found [calc](https://kaimei.org/use/study/calc) v2.12.7.1 (Nov 2018) compiled for Windows by some developer from Japan. I wrote to him asking for a binary update if possible. I'll let you know if that happens.

**Comment by lcn2** [comment]
> In the meantime, I've found [calc](https://kaimei.org/use/study/calc) v2.12.7.1 (Nov 2018) compiled for Windows by some developer from Japan. I wrote to him asking for a binary update if possible. I'll let you know if that happens.

Please do.  And if that developer from Japan wishes to  provide a URL for such a binary, we would be happy to publicize it.

SUGGESTION: Be sure that the binary is from at least version 2.17.0.0, @sergeevabc

**Comment by pmetzger** [comment]
Obviously if you prefer Windows 7 that's up to you. I think it does not make much sense having official support in Calc for old versions of Windows; they do not get security patches after all and the stats say they have vanishingly small numbers of users. I get that some people will always use such things — it's a big world and doubtless someone out there is still doing their daily computing on an old Microvax or something — but I generally think that to the extent that someone wants to create an official supported version of Calc for Windows, the obvious way to do that is WinGet, which is officially supported by Microsoft.

**Comment by flawrist** [comment]
@pmetzger 
Building apps around fleeting Silicon Valley trends is a fundamentally flawed approach. We should adopt technology to empower people and ease suffering, particularly in overlooked regions like the Brazilian [favelas](https://en.wikipedia.org/wiki/Favela) where Michael Jackson [sang](https://www.youtube.com/watch?v=QNJL6nfu__Q) “They don't care about us”.  Instead, you advocate for aligning life with corporate schedules and [arbitrary EOL dates](https://en.wikipedia.org/wiki/Planned_obsolescence) that force wasteful upgrades.

Microsoft is an IT hegemon, its decisions are driven by profit. Since delivering a stable and revolutionary product is no longer a viable strategy, they've sold the public on a narrative that OS is inherently broken and needs [constant patching](https://krebsonsecurity.com/2026/07/microsoft-patches-a-record-570-security-flaws/). When this artificial cycle no longer satisfies corporate growth, they simply pull the plug on support to stimulate demand for a shinier, newer OS — and right now, they're actually phasing out that ugly, data-harvesting Windows 10.

However, Windows 7 comes from an era with a different mindset. It is so well-refined that it will function reliably for the foreseeable future, so long as the hardware holds up — AliExpress is full of that. A sturdy hammer continues to drive nails long after its warranty expires or its manufacturer closes. Windows 7 is that hammer among Microsoft OSes — at least for home computing. To top it off, an unofficial [update channel](https://0patch.com/patches?product=Windows+7) exists.

As for the global market share of OSes, there is no single source of truth. When you are parroting sources like StatCounter, which use JavaScript beacons placed on “[1 million websites](https://gs.statcounter.com/faq#methodology)”, think again. For some reason, you won’t find these beacons on the websites of major retailers or social media platforms, and on other sites, they are mostly blocked by browser extensions like uBlock Origin. This renders their statistics completely unreliable.

However, the ongoing relevance of Windows 7 can be judged indirectly by community efforts to prolong its life. For example, Firefox has R3dfox and Chromium has Supermium. There are current Go, Node, and Python forks. Highly acclaimed CLI and GUI apps such as 7-zip, AutoHotkey, FFMPEG, Foobar2000, IrfanView, KeePass, MPC-HC, Sublime Text, Telegram work perfectly fine on Windows 7. There is even [VxKex](https://github.com/i486/VxKex), Windows 7 API extender, to run some Windows 10 apps, Those developers are true heroes of our digital age who refuse to let corporations rule the day.

Alas, dropping Windows entirely is not the universal answer, because an established workflow is not just a habit — it's an economic asset. For a middle-aged professional, a computer is a tool, not a hobby. Forcing such users to trade decades of muscle memory, specialized software, and local file habits for a completely different ecosystem (one of hundreds of Linux distros) isn't a simple upgrade — it's a long, frustrating period of retraining with uncertain prospects.

Previous generations envisioned computers as vehicles for human advancement, not luxuries. By treating vendors as deities and their decisions as laws of physics, we kill that dream and invite a new form of slavery. Bless those who compile Calc to ensure complex math stays widely accessible.

**Comment by lcn2** [comment]
> In the meantime, I've found calc v2.12.7.1 (Nov 2018) compiled for Windows by some developer from Japan. I wrote to him asking for a binary update if possible. I'll let you know if that happens.

Version 2.12.7.1 is **NOT** a recommended version of calc.  There are some significant bugs and issues in that version that have long since been fixed for several years in. As such we won't recommend publishing a link to such an old version.  

We suggest 2.17.0.0 or later. 

If someone wanted to publish a URL to a windows compiled calc version 2.17.0.0 (or later), we would be happy to mention that in our repo `README.md`, and under the `README.WINDOWS` source file.

## UPDATE 0a

Best wishes, @sergeevabc , on encouraging that developer to recompile the current version (2.17.0.0 or later) of calc. 

And if they run into any show stopper issues in compilation, let us know the details of their issues, as we might be able to help. 

## UPDATE 1b

If they run into issues in compiling 2.17.0.0 under that older version of Windows, then they should try compiling the legacy-calc branch.

The legacy-calc branch, while version 2.16.x.y, is currently at an equivalent level (bug fix wise) as 2.17.0.0.

## UPDATE 2a

The legacy-calc branch was also the last known version of calc that was reported to compile under OS/2 and DOS. Moreover those with 16-bit CPUs (and 16-bit CPUs that simulated 32-bit arithmetic, as well as some early 32-bit capable CPUs that lacked the ability to do 64-bit arithmetic) may wish to use the legacy-calc branch.

Going forward in calc version 3, where of the main drive is to support values larger than 256 Megabytes in size (calc v3 target max size is 256 Terabytes), we have had to leave behind such older processors because they lack the ability to access such large values.

So the legacy-calc branch was created to support such older processors.  That branch won't get new calc v3 functions (there is a lot planned beyond simply larger values).  Nevertheless if we do find a security issue, or a significant calculation bug whose fix can be back ported, we will make an effort to update the legacy-calc branch. 

## UPDATE 3

And speculating on what older Versions of Windows might require in terms of hardware, compilers, and C-ifdef stuff, they might find the legacy-calc branch useful.

There's nothing wrong with the current master branch as it currently holds a good calc version 2.17.0.0.  It is the default and supported calc. And if users of older processors, and/or uses of older operating systems are able to compile and use the master branch where calc version 2.17.0.0 currently reside, they **SHOULD USE THE MASTER BRACH**. 

The legacy-calc branch is only there as a fallback for those legacy processors and environments that can't use the current version of calc. 

We hope this helps and clarifies.
