### ISSUE TITLE
Use PREFIX (or somethign similar) instead of hard-coding install locations in Makefile

### ISSUE THREAD

**Issue by pmetzger** [lcn2/calc#27]
Howdy!

There are a lot of places in the Makefile that refer to `/usr/local` and the like. It would be neat if most of these were parameterized by a variable that could be passed in (something like `PREFIX` or what have you.) That way, package maintainers that want to install to a quite different place (to `/` or to `/opt/local` or what have you) could avoid needing to patch the Makefile.

Right now, for MacPorts, I maintain a patch file that does a lot of:

```
 # default LIBDIR for macOS
-LIBDIR= /usr/local/lib
+LIBDIR= ___PREFIX___/lib
```

type of machinery, followed by a `sed` pass that changes `___PREFIX___` to an appropriate value for the particular user. This could all be eliminated if instead it read

```
LIBDIR=${PREFIX}/lib
```

or some such.

**Comment by lcn2** [comment]
This is a good idea.

We will work on this for the 2.13.0.1 stable release.

**Comment by lcn2** [comment]
Please check out, @pmetzger the top of the master branch for a potential fix to this issue.

Comments, suggestions and corrections welcome.

**Comment by pmetzger** [comment]
I'll have a look now.

**Comment by pmetzger** [comment]
So it looks close. The one patch I would still seem to need is this, because (I think?) I need to put the created `include` files in a different place than the system ones that `INCDIR` points at:

```
 #
 #CALC_INCDIR= /usr/local/include/calc
 #CALC_INCDIR= /dev/env/DJDIR/include/calc
-CALC_INCDIR= ${INCDIR}/calc
+CALC_INCDIR= ___PREFIX___/include/calc
 
 # By default, these values are based CALC_SHAREDIR, INCDIR, BINDIR
 # ---------------------------------------------------------------
```

**Comment by pmetzger** [comment]
BTW, it appears that (modulo the `CALC_INCDIR` thing) this leaves only one set of patches I need to apply, for readline. My current patch for that is:

```
@@ -993,11 +993,11 @@
 #
 # If in doubt, set USE_READLINE, READLINE_LIB and READLINE_INCLUDE to nothing.
 #
-USE_READLINE=
-#USE_READLINE= -DUSE_READLINE
+#USE_READLINE=
+USE_READLINE= -DUSE_READLINE
 #
-READLINE_LIB=
-READLINE_EXTRAS=
+#READLINE_LIB=
+#READLINE_EXTRAS=
 #
 #READLINE_LIB= -lreadline
 #READLINE_EXTRAS= -lhistory -lncurses
@@ -1022,6 +1022,8 @@
 #
 #READLINE_LIB= -L/usr/local/opt/readline/lib -lreadline
 #READLINE_EXTRAS= -lhistory -lncurses
+READLINE_LIB= -L___PREFIX___/lib -lreadline
+READLINE_EXTRAS= -lhistory -lncurses
 #
 READLINE_INCLUDE=
 #READLINE_INCLUDE= -I/usr/gnu/include
```

**Comment by lcn2** [comment]
INCDIR depends on if the host target is Darwin based (macOS), or not. 
In the case of macOS, INCDIR must be calculated by xcrun:

    INCDIR= $(shell xcrun --show-sdk-path --sdk macosx)/usr/include

otherwise INCDIR is:

    INCDIR= /usr/include

In both cases, INCDIR is NOT under ${PREFIX} (i.e., not under /usr/local).

Unfortunately, CALC_INCDIR is the calc directory under INCDIR and this CALC_INCDIR cannot be under ${PREFIX}.
So we do not see a way that we can use ${PREFIX for CALC_INCDIR.
It appears you will have to set ${INCDIR} in addition to setting ${PREFIX} due to the nature of include files.

Sorry!

**Comment by lcn2** [comment]
We have hesitated to make the generic source dependent on the host being able to compile with readline because for hosts that do not have deadline AND/OR because different hosts require different paths and libs to support deadline.

The Makefile (as found in the GitHub master branch) does set the READLINE variables based on what homebrew does (in the case of the Darwin (macOS) target).  The Makefile.ship (as found in the GitHub master branch) does leaves READLINE variables empty.  Thus if you are compiling from the GitHub master branch, and you have homebrew installed, it works.

The calc source tarball is make with Makefile.ship moved in place of Makefile.  I.e., the calc tarball is different than the master branch (for a host of reasons). 

What about calling the Makefile.ship (or Makefile if you are using the calc tarball) with PREFIX, INCDIR and related READLINE values set as needed?

**Comment by lcn2** [comment]
Given the above limitations, we may have moved this as far as we  can go without impacting other build environments.

Hopefully we made the Makefile easier for you to manage.

**Comment by lcn2** [comment]
Here is another idea:  We just closed this issue: "Allow Makefile customizations in one place #11":

    https://github.com/lcn2/calc/issues/11

The Makefile includes Makefile.local:

    include Makefile.local

just before the first rule:

    all: check_include ${BLD_TYPE} CHANGES

Calc will ship with a Makefile.local file that just has a comment:

    # Add below to override Makefile values (using :=) as in: HAVE_STRING_H:= YES

You could put into Makefile.local, all of the values you wished.  For example, Makefile.local could override values:

    INCDIR:= /some/path/include
    CALC_INCDIR:= ${INCDIR}/calc
    USE_READLINE:= -DUSE_READLINE
    READLINE_LIB:= -L/some/path/lib -lreadline
    READLINE_EXTRAS:= -lhistory -lncurses

Does that help?

**Comment by pmetzger** [comment]
On the `CALC_INCDIR` issue, for me the issue is that `CALC_INCDIR` should not be under `INCDIR` in a MacPorts package.

The include mechanism probably does help! I can then set all of the locations in one place without needing to patch anything. I presume the values I set in `Makefile.local` override any other settings. That said, as an alternative, given that there are very few variables here to set, I could set them on the `make` command line, without needing the `Makefile.local`; I'm unsure what is cleaner.

 It might be useful for newcomers if you could document all the values that one is likely to want to modify, but that's a detail, as I already have a quite reasonable configuration for MacPorts.

**Comment by lcn2** [comment]
I recommend that you replace Makefile.local with what you need for MacPorts.

Fixed in v.2.13.0.1.

**Comment by pmetzger** [comment]
Just updated MacPorts. Had to still do a `sed` trick on the `Makefile.local`, but everything is much simpler and more maintainable now. Thank you! For reference, my Makefile.local now contains:

```
# Add below to override Makefile values (using :=) as in: HAVE_STRING_H:= YES
PREFIX=___PREFIX___
CALC_INCDIR:= ${PREFIX}/include/calc
USE_READLINE:= -DUSE_READLINE
READLINE_LIB:= -L${PREFIX}/lib -lreadline
READLINE_EXTRAS:= -lhistory -lncurses
```

Not 100% sure if the `PREFIX` shouldn't be followed by a `:=`; my make fu is too weak, but everything seems to work right and the patch should be dramatically easier to maintain going forward.
