### ISSUE TITLE
slight issue building 2.14.0.0 on MacOS

### ISSUE THREAD

**Issue by pmetzger** [lcn2/calc#32]
I often diff the resulting files on old and new versions of a package for MacPorts. We seem to be missing the dylib symlinks you normally get on a mac now. No idea why.

```
-/opt/local/lib/libcalc.2.13.0.1.dylib
-/opt/local/lib/libcalc.dylib
-/opt/local/lib/libcustcalc.2.13.0.1.dylib
-/opt/local/lib/libcustcalc.dylib
+/opt/local/lib/libcalc.2.14.0.0.dylib
+/opt/local/lib/libcustcalc.2.14.0.0.dylib
```

Note that before `libcalc.dylib` was a symlink to `libcalc.2.13.0.1.dylib`; beats me why these symlinks are now missing.

**Comment by lcn2** [comment]
Thanks for the report, we will look into it and resolve it before version 2.14.0.1 is released.

**Comment by lcn2** [comment]
Odd .. on macOS 11.15.2 we see the symlinks.

For example the make install rule produces:

# make install
installed /usr/local/bin/calc
installed /usr/local/share/calc/help/unexpected
installed /usr/local/share/calc/help/builtin
installed /usr/local/share/calc/help/errorcodes
installed /usr/local/share/calc/help/changes
installed /usr/local/share/calc/help/full
installed /usr/local/share/calc/help/d2g
installed /usr/local/share/calc/help/d2r
installed /usr/local/share/calc/help/g2d
installed /usr/local/share/calc/help/g2r
installed /usr/local/share/calc/help/r2d
installed /usr/local/share/calc/help/r2g
installed /usr/local/share/calc/help/change
installed /usr/local/share/calc/help/errorcode
installed /usr/local/share/calc/regress.cal
installed /usr/local/lib/libcalc.2.14.0.0.dylib
installed /usr/local/lib/libcalc.dylib
installed /usr/local/lib/libcustcalc.2.14.0.0.dylib
installed /usr/local/lib/libcalc.dylib
installed /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/calc/qmath.h

So that we have:

# ls -l /usr/local/lib/libcalc.2.14.0.0.dylib /usr/local/lib/libcalc.dylib /usr/local/lib/libcustcalc.2.14.0.0.dylib /usr/local/lib/libcalc.dylib
-rw-r--r--  1 root  sysadm  841592 Sep  7 13:35 /usr/local/lib/libcalc.2.14.0.0.dylib
lrwxr-xr-x  1 root  sysadm      22 Sep  7 13:35 /usr/local/lib/libcalc.dylib -> libcalc.2.14.0.0.dylib
lrwxr-xr-x  1 root  sysadm      22 Sep  7 13:35 /usr/local/lib/libcalc.dylib -> libcalc.2.14.0.0.dylib
-rw-r--r--  1 root  sysadm   53352 Sep  7 13:35 /usr/local/lib/libcustcalc.2.14.0.0.dylib

When we clobber and make all:

# make clobber all 

We see:

-rwxr-xr-x    1 chongo  src  841592 Sep  7 13:43 libcalc.2.14.0.0.dylib
lrwxr-xr-x    1 chongo  src      22 Sep  7 13:43 libcalc.dylib -> libcalc.2.14.0.0.dylib
-rwxr-xr-x    1 chongo  src   53352 Sep  7 13:43 libcustcalc.2.14.0.0.dylib
lrwxr-xr-x    1 chongo  src      26 Sep  7 13:43 libcustcalc.dylib -> libcustcalc.2.14.0.0.dylib

**Comment by lcn2** [comment]
Sorry, we are unable to reproduce with the top of the master branch on macOS 11.5.2.

Please retest and advise, thanks!

**Comment by lcn2** [comment]
If it matters, we are using Xcode v12.5.1 (12E507).

**Comment by pmetzger** [comment]
It appears that the bug is not in the build but in my package version comparison tool, which I inadvertently broke a few weeks ago. Apologies for inconveniencing you.

**Comment by lcn2** [comment]
Thanks for the followup.
